name: football-recruitment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - statsbombpy
      - pandas
      - numpy
      - scipy
      - scikit-learn
      - pyarrow
      - matplotlib
      - plotly
      - streamlit
      - mplsoccer
      - jupyterlab
      - pytest

